version: '3'

services:
  sample:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app/frontend'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development