version: '2'

services:
    react-frontend:
        container_name: react-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/usr/src/app/frontend'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development

    node-backend:
        container_name: node-backend
        image: node-backend
        build: 
            context: ./api
            dockerfile: Dockerfile
        networks:
            - backend
        ports:
            - "8081:8081"
        volumes:
            - ./api/:/usr/src/app/api

    web-cli:
        image: node-backend
        networks:
            - backend
        command: sh

    db:
        container_name: mysql-db
        image: mysql:latest
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password

networks:
    backend:
        driver: bridge