version: '2'
services:
    flask-web:
        build: 
            context: ./flask_api
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./flask_api:/code