version: '2'

services:
    react-frontend:
        container_name: react-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/usr/src/app/frontend'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development

    node-backend:
        container_name: node-backend
        image: node-backend
        build: 
            context: ./api
            dockerfile: Dockerfile
        networks:
            - backend
        ports:
            - "8081:8081"
        volumes:
            - ./api/:/usr/src/app/api
            - /app/node_modules/

    web-cli:
        image: node-backend
        command: sh

    mongo:
        container_name: mongo
        image: mongo:latest
        networks: 
            - backend

        volumes:
            - ./mongo-database:/data/db

networks:
    backend:
        driver: bridge